stages:
  - deploy

maven-build-test-deploy:
  image: maven:3.6.3-openjdk-11
  stage: deploy
  script:
    - echo $(mvn --version)
    - echo $(java --version)
    - mvn clean install
    - echo "pushing to $CI_COMMIT_REF_NAME"
    - mvn compile jib:build -Djib.to.image=docker.io/"$DOCKERHUB_REPO"/pdx-validator:"$CI_COMMIT_REF_NAME" -Djib.to.auth.username="$DOCKERHUB_USER" -Djib.to.auth.password="$DOCKERHUB_TOKEN"
    - echo "mvn compile jib:build -Djib.to.image=dockerhub.ebi.ac.uk/mouse-informatics/pdxfinder-validator -Djib.to.auth.username="$CI_REGSITRY_USER" -Djib.to.auth.password="$CI_REGSITRY_PASSWORD"
    - mvn compile jib:dockerBuild -Djib.to.image=dockerhub.ebi.ac.uk/mouse-informatics/pdxfinder-validator -Djib.to.auth.username="$CI_REGSITRY_USER" -Djib.to.auth.password="$CI_REGSITRY_PASSWORD"