stages:
  - deploy

maven-build-test-deploy:
  image: maven:3.6.3-openjdk-11
  stage: deploy
  script:
    - echo $(mvn --version)
    - echo $(java --version)
    - mvn clean install
    - echo "pushing to $CI_COMMIT_REF_NAME"
    - mvn compile jib:build -Djib.to.image=docker.io/"$DOCKERHUB_REPO"/pdx-validator:"$CI_COMMIT_REF_NAME" -Djib.to.auth.username="$DOCKERHUB_USER" -Djib.to.auth.password="$DOCKERHUB_TOKEN"
    - mvn compile jib:build -Djib.to.auth.username=${CI_REGISTRY_USER} -Djib.to.auth.password=${CI_REGISTRY_PASSWORD} -Djib.to.image=${CI_REGISTRY_IMAGE}:"$CI_COMMIT_REF_NAME"