apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdx-validator-dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pdx-validator
    spec:
      containers:
        - name: pdx-validator
          image: 'pdxfinder/pdx-validator:dev'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pdx-validator-dev-service
  labels:
    name: pdx-validator-dev-service
spec:
  ports:
    - port: 8080
      protocol: HTTP
  selector:
    app: pdx-validator
  type: NodePort

